import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, Check, FileText, Pencil, Plus, Printer, Search, X } from 'lucide-react';
import { api, patch, post, type CustomerInvoice, type InvoiceListRow, type InvoiceSettings, type Job, type SaleItem } from './api';

const money = (paise: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(paise / 100);
const date = (value: string | null) => value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Not issued';
const errorText = (cause: unknown) => cause instanceof Error ? cause.message : 'Request failed';
type DraftLine = { kind: 'ADD_ON' | 'PRODUCT' | 'CUSTOM'; saleItemId?: string; description?: string; quantity: number; unitPricePaise?: number };
function draftLines(job: Job): DraftLine[] { return job.invoice?.status === 'DRAFT' ? job.invoice.items.filter((item) => item.kind !== 'SERVICE').map((item) => item.kind === 'CUSTOM' ? { kind: 'CUSTOM', description: item.description, quantity: item.quantity, unitPricePaise: item.unitPricePaise / 100 } : { kind: item.kind as 'ADD_ON' | 'PRODUCT', saleItemId: item.saleItemId ?? '', quantity: item.quantity }) : []; }

export function JobInvoicePanel({ job, onChanged }: { job: Job; onChanged: () => void }) {
  const [catalog, setCatalog] = useState<SaleItem[]>([]);
  const [settings, setSettings] = useState<InvoiceSettings | null>(null);
  const [lines, setLines] = useState<DraftLine[]>(() => draftLines(job));
  const [discountKind, setDiscountKind] = useState<'NONE' | 'FLAT' | 'PERCENT'>(() => job.invoice?.status === 'DRAFT' ? job.invoice.discountKind : 'NONE');
  const [discount, setDiscount] = useState(() => job.invoice?.status === 'DRAFT' ? String(job.invoice.discountValue / 100) : '0');
  const [payment, setPayment] = useState('');
  const [method, setMethod] = useState('UPI');
  const [reason, setReason] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => {
    void Promise.all([api<SaleItem[]>('/sale-items'), api<InvoiceSettings>('/invoice-settings')]).then(([items, options]) => { setCatalog(items.filter((item) => item.active)); setSettings(options); }).catch((cause) => setError(errorText(cause)));
  }, []);
  async function perform(work: () => Promise<unknown>) {
    setBusy(true); setError('');
    try { await work(); onChanged(); }
    catch (cause) { setError(errorText(cause)); }
    finally { setBusy(false); }
  }
  async function save(event: FormEvent) {
    event.preventDefault();
    await perform(() => post(`/jobs/${job.id}/invoice`, { items: lines.map((line) => line.kind === 'CUSTOM' ? { ...line, unitPricePaise: Math.round((line.unitPricePaise ?? 0) * 100) } : line), discountKind, discountValue: discountKind === 'NONE' ? 0 : Math.round(Number(discount) * 100) }));
  }
  const invoice = job.invoice;
  return <section className="ops-detail-section invoice-job-panel"><h3>Customer invoice</h3>
    {invoice && <><p><strong>{invoice.invoiceNumber}</strong> · {invoice.status.replaceAll('_', ' ')}</p><div className="ops-bill-row"><span>Total</span><strong>{money(invoice.totalPaise)}</strong></div><div className="ops-bill-row"><span>Paid</span><strong>{money(job.paidPaise ?? 0)}</strong></div><div className="ops-bill-row"><span>Outstanding</span><strong>{money(job.outstandingPaise ?? 0)}</strong></div><a className="btn ghost" href={`/invoices/${invoice.id}`}><FileText size={16} />View invoice</a></>}
    {job.status !== 'HANDED_OVER' && (!invoice || invoice.status === 'DRAFT' || invoice.status === 'CANCELLED') && <form className="ops-form invoice-draft-form" onSubmit={(event) => void save(event)}><p>Service: {job.serviceName}</p>
      {lines.map((line, index) => <div className="invoice-edit-line" key={index}><select className="input" aria-label={`Item ${index + 1}`} value={line.kind === 'CUSTOM' ? 'CUSTOM' : line.saleItemId} onChange={(event) => { const value = event.target.value; const choice = catalog.find((item) => item.id === value); setLines(lines.map((item, at) => at === index ? value === 'CUSTOM' ? { kind: 'CUSTOM', description: '', quantity: 1, unitPricePaise: 0 } : { kind: choice?.kind ?? 'ADD_ON', saleItemId: value, quantity: 1 } : item)); }} required><option value="">Select item</option>{catalog.map((item) => <option value={item.id} key={item.id}>{item.kind === 'ADD_ON' ? 'Add-on' : 'Product'} · {item.name} · {money(item.pricePaise ?? 0)}</option>)}{settings?.allowCustomInvoiceItems && <option value="CUSTOM">Custom item</option>}</select><input className="input" type="number" min="1" max="100" aria-label={`Item ${index + 1} quantity`} value={line.quantity} onChange={(event) => setLines(lines.map((item, at) => at === index ? { ...item, quantity: Number(event.target.value) } : item))} /> <button type="button" className="icon-btn" aria-label={`Remove item ${index + 1}`} title="Remove item" onClick={() => setLines(lines.filter((_, at) => at !== index))}><X size={16} /></button>{line.kind === 'CUSTOM' && <><input className="input" placeholder="Description" aria-label={`Custom item ${index + 1} description`} value={line.description ?? ''} onChange={(event) => setLines(lines.map((item, at) => at === index ? { ...item, description: event.target.value } : item))} required /><input className="input" type="number" min="0" step="0.01" aria-label={`Custom item ${index + 1} price in rupees`} value={line.unitPricePaise ?? 0} onChange={(event) => setLines(lines.map((item, at) => at === index ? { ...item, unitPricePaise: Number(event.target.value) } : item))} /></>}</div>)}
      <button type="button" className="btn ghost" onClick={() => setLines([...lines, { kind: 'ADD_ON', saleItemId: '', quantity: 1 }])}><Plus size={16} />Add line</button>
      <div className="ops-form-grid"><label className="field"><span>Discount</span><select className="input" value={discountKind} onChange={(event) => setDiscountKind(event.target.value as typeof discountKind)}><option value="NONE">None</option><option value="FLAT">Flat amount</option><option value="PERCENT">Percentage</option></select></label>{discountKind !== 'NONE' && <label className="field"><span>{discountKind === 'PERCENT' ? 'Percent' : 'Amount (INR)'}</span><input className="input" type="number" min="0" max={discountKind === 'PERCENT' ? '100' : undefined} step="0.01" value={discount} onChange={(event) => setDiscount(event.target.value)} /></label>}</div>
      <button className="btn primary" disabled={busy}>{invoice?.status === 'DRAFT' ? 'Update draft' : invoice?.status === 'CANCELLED' ? 'Create replacement draft' : 'Create invoice draft'}</button>
    </form>}
    {invoice?.status === 'DRAFT' && <button type="button" className="btn primary" disabled={busy} onClick={() => void perform(() => post(`/invoices/${invoice.id}/issue`, {}))}>Issue invoice</button>}
    {invoice && invoice.status !== 'DRAFT' && invoice.status !== 'CANCELLED' && (job.outstandingPaise ?? 0) > 0 && <form className="ops-form" onSubmit={(event) => { event.preventDefault(); void perform(() => post(`/jobs/${job.id}/payments`, { idempotencyKey: crypto.randomUUID(), amountPaise: Math.round(Number(payment) * 100), method })); setPayment(''); }}><div className="ops-form-grid"><label className="field"><span>Collect (INR)</span><input className="input" type="number" step="0.01" min="0.01" max={(job.outstandingPaise ?? 0) / 100} value={payment} onChange={(event) => setPayment(event.target.value)} required /></label><label className="field"><span>Method</span><select className="input" value={method} onChange={(event) => setMethod(event.target.value)}>{['UPI', 'CASH', 'CARD', 'BANK_TRANSFER', 'OTHER'].map((value) => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></label></div><button className="btn ghost" disabled={busy}>Record payment</button></form>}
    {invoice && job.status !== 'HANDED_OVER' && (job.paidPaise ?? 0) === 0 && <form className="ops-form" onSubmit={(event) => { event.preventDefault(); void perform(() => post(`/invoices/${invoice.id}/cancel`, { reason })); }}><label className="field"><span>Cancel reason</span><input className="input" value={reason} onChange={(event) => setReason(event.target.value)} minLength={5} required /></label><button className="btn ghost" disabled={busy}>Cancel invoice</button></form>}
    {error && <p className="portal-error" role="alert">{error}</p>}
  </section>;
}

function InvoiceDocument({ invoice }: { invoice: CustomerInvoice }) {
  return <article className="invoice-document"><header className="invoice-document-head"><div><img src="/kleenbay-monogram.png" alt="KleenBay" /><h2>{invoice.organization.name}</h2><p>{invoice.organization.invoiceAddress || invoice.job.branch.address}</p><p>{invoice.organization.invoicePhone || invoice.job.branch.phone}</p>{invoice.organization.gstin && <p>GSTIN: {invoice.organization.gstin}</p>}</div><div><h1>Invoice</h1><strong>{invoice.invoiceNumber}</strong><p>{date(invoice.issuedAt ?? invoice.createdAt)}</p><p>{invoice.status.replaceAll('_', ' ')}</p></div></header>
    <div className="invoice-parties"><div><small>Billed to</small><strong>{invoice.job.customer.name}</strong><span>{invoice.job.customer.mobile}</span></div><div><small>Vehicle and service</small><strong>{invoice.job.vehicle.registrationNumber}</strong><span>{invoice.job.vehicle.make} {invoice.job.vehicle.model}</span><span>{invoice.job.serviceName} · Job #{invoice.job.number}</span></div></div>
    <div className="invoice-table-wrap"><table className="tbl invoice-table"><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Tax</th><th>Total</th></tr></thead><tbody>{invoice.items.map((item) => <tr key={item.id}><td><strong>{item.description}</strong><small>{item.kind.replaceAll('_', ' ')}</small></td><td>{item.quantity}</td><td>{money(item.unitPricePaise)}</td><td>{money(item.taxPaise)}</td><td>{money(item.totalPaise)}</td></tr>)}</tbody></table></div>
    <div className="invoice-totals"><div><span>Subtotal</span><strong>{money(invoice.subtotalPaise)}</strong></div><div><span>Discount{invoice.discountKind === 'PERCENT' ? ` (${invoice.discountValue / 100}%)` : ''}</span><strong>-{money(invoice.discountPaise)}</strong></div><div><span>Taxable amount</span><strong>{money(invoice.taxablePaise)}</strong></div><div><span>Tax</span><strong>{money(invoice.taxPaise)}</strong></div><div className="invoice-grand"><span>Total</span><strong>{money(invoice.totalPaise)}</strong></div><div><span>Paid</span><strong>{money(invoice.paidPaise)}</strong></div><div><span>Outstanding</span><strong>{money(invoice.outstandingPaise)}</strong></div></div>
    <section className="invoice-payment-list"><h3>Payments</h3>{invoice.payments.length ? invoice.payments.map((payment) => <p key={payment.id}>{date(payment.createdAt)} · {payment.method.replaceAll('_', ' ')} · {money(payment.amountPaise)}{payment.reference ? ` · ${payment.reference}` : ''}</p>) : <p>No payments recorded.</p>}</section><footer>Thank you for choosing {invoice.organization.name}.</footer>
  </article>;
}

export function InvoicesView() {
  const pathId = /^\/invoices\/([^/]+)(?:\/print)?$/.exec(window.location.pathname)?.[1];
  const [selectedId, setSelectedId] = useState(pathId ?? '');
  const [printMode, setPrintMode] = useState(window.location.pathname.endsWith('/print'));
  const [rows, setRows] = useState<InvoiceListRow[]>([]);
  const [invoice, setInvoice] = useState<CustomerInvoice | null>(null);
  const [query, setQuery] = useState('');
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [tab, setTab] = useState<'invoices' | 'items' | 'settings'>('invoices');
  const [catalog, setCatalog] = useState<SaleItem[]>([]);
  const [settings, setSettings] = useState<InvoiceSettings | null>(null);
  const [newKind, setNewKind] = useState<'ADD_ON' | 'PRODUCT'>('ADD_ON');
  const [newName, setNewName] = useState('');
  const [newPrice, setNewPrice] = useState('');
  const [editingId, setEditingId] = useState('');
  const [editName, setEditName] = useState('');
  const [editPrice, setEditPrice] = useState('');
  const [collectAmount, setCollectAmount] = useState('');
  const [collectMethod, setCollectMethod] = useState('UPI');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const reloadCatalog = useCallback(() => { void api<SaleItem[]>('/sale-items').then(setCatalog).catch((cause) => setError(errorText(cause))); }, []);
  useEffect(() => { reloadCatalog(); void api<InvoiceSettings>('/invoice-settings').then(setSettings).catch((cause) => setError(errorText(cause))); }, [reloadCatalog]);
  useEffect(() => { const timer = setTimeout(() => { const params = new URLSearchParams(); if (query) params.set('q', query); if (from) params.set('from', from); if (to) params.set('to', to); void api<InvoiceListRow[]>(`/invoices?${params}`).then(setRows).catch((cause) => setError(errorText(cause))); }, 200); return () => clearTimeout(timer); }, [query, from, to]);
  useEffect(() => { if (selectedId) void api<CustomerInvoice>(`/invoices/${selectedId}`).then(setInvoice).catch((cause) => setError(errorText(cause))); }, [selectedId]);
  function open(id: string, print = false) { setSelectedId(id); setInvoice(null); setPrintMode(print); window.history.pushState(null, '', `/invoices/${id}${print ? '/print' : ''}`); }
  function back() { setSelectedId(''); setInvoice(null); setPrintMode(false); window.history.pushState(null, '', '/invoices'); }
  async function addItem(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await post('/sale-items', { kind: newKind, name: newName, pricePaise: Math.round(Number(newPrice) * 100), active: true }); setNewName(''); setNewPrice(''); reloadCatalog(); } catch (cause) { setError(errorText(cause)); } finally { setBusy(false); } }
  async function saveItem(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await patch(`/sale-items/${editingId}`, { name: editName, pricePaise: Math.round(Number(editPrice) * 100) }); setEditingId(''); reloadCatalog(); } catch (cause) { setError(errorText(cause)); } finally { setBusy(false); } }
  async function saveSettings(event: FormEvent) { event.preventDefault(); if (!settings) return; setBusy(true); setError(''); try { setSettings(await patch<InvoiceSettings>('/invoice-settings', settings)); } catch (cause) { setError(errorText(cause)); } finally { setBusy(false); } }
  async function collect(event: FormEvent) { event.preventDefault(); if (!invoice) return; setBusy(true); setError(''); try { await post(`/jobs/${invoice.jobId}/payments`, { idempotencyKey: crypto.randomUUID(), amountPaise: Math.round(Number(collectAmount) * 100), method: collectMethod }); setCollectAmount(''); setInvoice(await api<CustomerInvoice>(`/invoices/${invoice.id}`)); } catch (cause) { setError(errorText(cause)); } finally { setBusy(false); } }
  return <div className={`invoices-page${printMode ? ' invoice-print-mode' : ''}`}>
    {selectedId ? <><div className="invoice-toolbar"><button type="button" className="btn ghost" onClick={back}><ArrowLeft size={17} />Invoices</button><button type="button" className="btn primary" onClick={() => { setPrintMode(true); window.history.replaceState(null, '', `/invoices/${selectedId}/print`); window.setTimeout(() => window.print(), 50); }}><Printer size={17} />Print / Save PDF</button></div>{invoice && <><InvoiceDocument invoice={invoice} />{invoice.status !== 'DRAFT' && invoice.status !== 'CANCELLED' && invoice.outstandingPaise > 0 && <form className="panel invoice-catalog-form" onSubmit={(event) => void collect(event)}><h3>Record payment</h3><div className="ops-form-grid"><label className="field"><span>Amount (INR)</span><input className="input" type="number" min="0.01" max={invoice.outstandingPaise / 100} step="0.01" value={collectAmount} onChange={(event) => setCollectAmount(event.target.value)} required /></label><label className="field"><span>Method</span><select className="input" value={collectMethod} onChange={(event) => setCollectMethod(event.target.value)}>{['UPI', 'CASH', 'CARD', 'BANK_TRANSFER', 'OTHER'].map((value) => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></label></div><button className="btn primary" disabled={busy}>Save payment</button></form>}</>}</> : <><nav className="settings-tabs" aria-label="Invoice sections"><button className={tab === 'invoices' ? 'active' : ''} onClick={() => setTab('invoices')}>Invoices</button><button className={tab === 'items' ? 'active' : ''} onClick={() => setTab('items')}>Add-ons and products</button><button className={tab === 'settings' ? 'active' : ''} onClick={() => setTab('settings')}>Invoice settings</button></nav>
      {tab === 'invoices' && <><div className="board-bar ops-board-bar"><label className="ops-search"><Search size={18} /><input aria-label="Search invoices" placeholder="Invoice, vehicle, customer or mobile" value={query} onChange={(event) => setQuery(event.target.value)} /></label><input className="input ops-date-filter" type="date" aria-label="From date" value={from} onChange={(event) => setFrom(event.target.value)} /><input className="input ops-date-filter" type="date" aria-label="To date" value={to} onChange={(event) => setTo(event.target.value)} /></div><div className="invoice-list">{rows.map((row) => <button key={row.id} type="button" className="invoice-row" onClick={() => open(row.id)}><FileText size={19} /><span><strong>{row.invoiceNumber}</strong><small>{row.job.customer.name} · {row.job.vehicle.registrationNumber}</small></span><span>{date(row.issuedAt ?? row.createdAt)}</span><span>{row.status.replaceAll('_', ' ')}</span><b>{money(row.totalPaise)}</b><small>Due {money(row.outstandingPaise)}</small></button>)}{!rows.length && <div className="empty">No customer invoices match these filters.</div>}</div></>}
      {tab === 'items' && <><form className="panel invoice-catalog-form" onSubmit={(event) => void addItem(event)}><h3>Add item</h3><div className="ops-form-grid"><label className="field"><span>Type</span><select className="input" value={newKind} onChange={(event) => setNewKind(event.target.value as typeof newKind)}><option value="ADD_ON">Add-on</option><option value="PRODUCT">Product</option></select></label><label className="field"><span>Name</span><input className="input" value={newName} onChange={(event) => setNewName(event.target.value)} required /></label><label className="field"><span>Price (INR)</span><input className="input" type="number" min="0" step="0.01" value={newPrice} onChange={(event) => setNewPrice(event.target.value)} required /></label></div><button className="btn primary" disabled={busy}>Add item</button></form><div className="invoice-catalog-list">{catalog.map((item) => <div key={item.id} className="invoice-catalog-row">{editingId === item.id ? <form className="invoice-catalog-edit" onSubmit={(event) => void saveItem(event)}><input className="input" aria-label={`${item.name} name`} value={editName} onChange={(event) => setEditName(event.target.value)} required /><input className="input" aria-label={`${item.name} price in rupees`} type="number" min="0" step="0.01" value={editPrice} onChange={(event) => setEditPrice(event.target.value)} required /><button className="icon-btn" aria-label="Save item" title="Save item" disabled={busy}><Check size={16} /></button><button type="button" className="icon-btn" aria-label="Cancel edit" title="Cancel edit" onClick={() => setEditingId('')}><X size={16} /></button></form> : <><span><strong>{item.name}</strong><small>{item.kind === 'ADD_ON' ? 'Add-on' : 'Product'} · {item.active ? 'Active' : 'Inactive'}</small></span><b>{money(item.pricePaise ?? 0)}</b><button type="button" className="icon-btn" aria-label={`Edit ${item.name}`} title="Edit item" onClick={() => { setEditingId(item.id); setEditName(item.name); setEditPrice(String((item.pricePaise ?? 0) / 100)); }}><Pencil size={16} /></button><button type="button" className="btn ghost" onClick={() => { void patch(`/sale-items/${item.id}`, { active: !item.active }).then(reloadCatalog).catch((cause) => setError(errorText(cause))); }}>{item.active ? 'Deactivate' : 'Activate'}</button></>}</div>)}</div></>}
      {tab === 'settings' && settings && <form className="panel invoice-settings-form" onSubmit={(event) => void saveSettings(event)}><h3>Invoice settings</h3><div className="ops-form-grid"><label className="field"><span>GST rate (%)</span><input className="input" type="number" min="0" max="100" step="0.01" placeholder="Not configured" value={settings.gstRateBps === null ? '' : String(settings.gstRateBps / 100)} onChange={(event) => setSettings({ ...settings, gstRateBps: event.target.value ? Math.round(Number(event.target.value) * 100) : null })} /></label><label className="field"><span>GSTIN (optional)</span><input className="input" value={settings.gstin ?? ''} onChange={(event) => setSettings({ ...settings, gstin: event.target.value || null })} /></label><label className="field"><span>Business phone</span><input className="input" value={settings.invoicePhone ?? ''} onChange={(event) => setSettings({ ...settings, invoicePhone: event.target.value || null })} /></label></div><label className="field"><span>Invoice address</span><textarea className="input ops-textarea" rows={2} value={settings.invoiceAddress ?? ''} onChange={(event) => setSettings({ ...settings, invoiceAddress: event.target.value || null })} /></label><label className="ops-toggle"><input type="checkbox" checked={settings.allowCustomInvoiceItems} onChange={(event) => setSettings({ ...settings, allowCustomInvoiceItems: event.target.checked })} /> Allow owner custom invoice items</label><label className="ops-toggle"><input type="checkbox" checked={settings.employeeAddons} onChange={(event) => setSettings({ ...settings, employeeAddons: event.target.checked })} /> Allow employee add-on selection</label><button className="btn primary" disabled={busy}>Save settings</button></form>}
    </>}{error && <p className="portal-error" role="alert">{error}</p>}
  </div>;
}
