apiVersion: v1
kind: ConfigMap
metadata:
  name: kleenbay-stage-config
  namespace: kleenbay-stage
data:
  NODE_ENV: production
  STAGING_MODE: "true"
  DEV_OTP_ENABLED: "false"
  OTP_PROVIDER: DUMMY_OTP
  DUMMY_OTP: "123456"
  MESSAGING_PROVIDER: mock
  RAZORPAY_ENV: test
  SUBSCRIPTION_GRACE_DAYS: "7"
  STORAGE_PROVIDER: s3
  S3_BUCKET: kleenbay-stage-uploads-208519604276
  S3_REGION: us-east-1
  AWS_EC2_METADATA_DISABLED: "true"
  MOCK_MESSAGING_FAIL: "false"
  APP_ORIGIN: https://stage.kleenbay.com
  COOKIE_SECURE: "true"
  HOST: 0.0.0.0
  PORT: "3000"
  TRUST_PROXY_HOPS: "1"
  EXPECTED_DATABASE_NAME: kleenbay_stage
  LOG_LEVEL: info
