apiVersion: batch/v1
kind: Job
metadata:
  generateName: kleenbay-stage-migrate-
  namespace: kleenbay-stage
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: migrate
          image: 208519604276.dkr.ecr.us-east-1.amazonaws.com/kleenbay/stage-api@sha256:dd43846627bc33dabebe7224cc0484015c7a9a1f8b81fe75d6c5a2b6f233d0d3
          command: ["./node_modules/.bin/prisma", "migrate", "deploy"]
          envFrom:
            - configMapRef:
                name: kleenbay-stage-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: kleenbay-stage-migrator-db
                  key: DATABASE_URL
