apiVersion: batch/v1
kind: Job
metadata:
  generateName: kleenbay-stage-migrate-
  namespace: kleenbay-stage
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: migrate
          image: 208519604276.dkr.ecr.us-east-1.amazonaws.com/kleenbay/stage-api@sha256:bd0333dd3d12c1720090695d1a900c2ac758a661a7f156e1733f4673b8913543
          command: [sh, -c, "cd apps/api && ./node_modules/.bin/prisma migrate deploy"]
          envFrom:
            - configMapRef:
                name: kleenbay-stage-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: kleenbay-stage-migrator-db
                  key: DATABASE_URL
